name: collab_task_backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.1.0
  equatable: ^2.0.5
  uuid: ^4.0.0
  sqlite3: ^2.4.0
  path: ^1.8.3
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
